### ISSUE TITLE
survHIMA

### ISSUE THREAD

**Issue by FloPittion** [YinanZheng/HIMA#9]
Hi,
At beginning of survHIMA function you wrote
n <- nrow(M)
p <- nrow(M)

Is this what you meant instead?
n <- nrow(M)
p <- ncol(M)
I have the impression that this causes an error when I want to run the function, but if I modify the code locally, it works.

**Comment by YinanZheng** [comment]
Thank you for catching this error! You are right! We will fix it in the next coming version very soon.

**Comment by YinanZheng** [comment]
Solved in the latest version, 2.3.0 (see GitHub). CRAN will be online by the end of October.
